AllCops:
  Exclude:
    - bin/**/*
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - swagger_docs_generator.gemspec

Style/TrivialAccessors:
  Exclude:
    - lib/swagger_docs_generator/parser/**/*

Performance/RedundantMerge:
  Exclude:
    - lib/swagger_docs_generator/parser/**/*
