sudo: false

language: ruby

rvm:
  - 2.4.0
  - 2.3.1

before_install:
  - bundle update
  - gem update --system

script:
  - rake

before_deploy:
  - gem install dpl

deploy:
  provider: rubygems
  api_key:
    secure: PTdpJ5M6TxbPJlnNCO1K9R206ogJZuSCl10ZhkvVzpu8hUJhNOIMzAa2sCv7PoYt/zQR1g378+mnB/y8CYU6c0KRFCkUxLq6qWSJrBjnH5jv/+oLwsPf7cyyWdWe420fSbUffaT+NkWTchKDJ65nNYxlCCJi2Q4aBKiygOt/L+WcxqN7uXE6Q3ubng6Z8Vc5ViHqpIC3m2EgJsHz46ovUZfOc+RHspOdccbqjlj9cEUVeEkth5ECe9zvINf/3tbn9PzeWKMJ/IJE3ZblVdudQVnaTtmT2j/0UiSkh2GAnT2pG9avNKnDfV65miYc9W/lrCCAj8B38bkK79fGdPM8v0/n6JXhTe2kzlzHf2qxYikrwUq2v9Bb28p6naK8xiB86tmmY01zV0s1UGSJoSFfc3tgT4X9p/gE4nbrV3up0qQvI84WRyXhgxi2Ud2+OYc/Tl6gBorDJt5madYmt6qY7AzrUqqbltw/319gmgcwxNkWqSvqil6RBh72wQ49lOa9AubFs016rpnU6Hwy3DTNnfE3EvOyPKnFvQ0iEdmKgoWDTZROY63REzdYfVUeXCR9Ujd1uH3F5ZNFe7mk9ZAM87cs/2pJoROM8mglYA54mycPvfz7A8jGpiGbiOLOatBk9/vrZtzBqWY3AfcvQ8BRZ/qKk13LQsdQH8m1y/aerfs=
  gem: swagger_docs_generator
  on:
    repo: Dev-Crea/swagger-docs-generator
    all_branches: true
  skip_cleanup: true

notifications:
  email: false
  slack:
    on_success: always
    rooms:
      secure: FE2l+y/mbui9/vH1XWaNK51DQBtRPPaOyrnJz7OUMox26eiLMKPtWYpg0JOVSb2HBMg20EagTgHwzrUWMy57zWfNJwg5CVqAkFv/GUK+FOzG6htvZJ8EiPXV/B/JtlVlV+Bue583jqSACLjFZyU6qTOyMn4EsHPWWsFTAmHiC3TV3VEVwkV4N5JA/YiB3PDzUMtcNV8ikz1m7gbPMosHqqyMiio31vCITKvci9P1gFIDZZex0h9/bVTd1DL7FuRP8YiGnRxGOGK2F7IAcrwggKclVJ6PRpJNzMaKbTOY6yXJHtYoNJThaCI+gGeecSl8Kcx5J5GKhhKqDMKKzbSojl1fAAOV8H0kRa30I+P2qRrp1wdj/KWRgOj+UNtt+17seNTfQC5z3QepSaIYyYvk9PlHCNI2e8NrYTk4nDX2UFqqHWQ8nIRKxqoWSLlrUjEoTRbO6nS6s0vzuvrbcR0vgkI0cvgvJ10tPtPBz7RfVXsPsv+0FqWfGUR3pfxHIsbBh3/TGxcyNA3nAxZKgv6MNpY/YF1NEX9iGwmeNO64gFO4kt4tZG9gXAPAD1LGlWKaeQ91mYe/YNQDiwUuPguAqkfjcR21Wrld4LbSnvcK7HWo0rV3t5ikeGITGsc4Nnthhu9tE/pP63Zhoa1lqLWXZyyti+lWES8Ov7ib5RHKGD4=
