sudo: false

language: ruby

rvm:
  - 2.4.0
  - 2.3.1

before_install:
  - bundle update
  - gem update --system

script:
  - rake

before_deploy:
  - gem install dpl

deploy:
  provider: rubygems
  api_key:
    secure: Vkhh5xBPJ1r1w3m8002wRiMStreBhXiTZwDck+iyMiZf3RqYmqndG7bx3XFvgGuQnKeyEva6FgZ9HuD3zIQ3TFFx7kl79TA6DSmrMfdNH9uauuK+9xSKXa30/E4dnZI7yKr+KsAAwTV0Ay5nlqpJ2r7m3fRsiH+EEZogCgRfd+Qgvu6boKiu9v0sSwE3vSY6RWfrVG3TigKHRWx/omW2Br3r6uTHQU2l/UsGlKCrkycugcmKoBdFN96wsAY07scAtuG4j/rKzSBZjQZGVKus1mBgXjVE6ODinW5h4TtR0w3MtvSsQRF00NHNRbNZDsnnivYhQRWKRVwahSaTlxWvdaxqb4B1bxFXRe4rvjsEsQv5linynz1o1ruHzRLsFuFPPL8An9HopskDyIutn/1Z0NDdM2OTKpMlqr8DbNhP9AXI8k3ld7yLuwHriPLH/xDKU9hBjHBR8Sk0YSjiUxZAvuseK7ktzeRibSseEMo1MZJuD4j3zvPHWVBp/OXRJKhBeTdfGZutH5sbwUe8DKQTnJ3ElQ4VBjHVJ+WWsQGZti0QFHZlMsPgp0K7tHq4gx0cQslq+d6aw6eJvCJdlbCSlKo8o5yKINsi61R3+8AaHpGlsXsbCpU7i7qSTIEc8bHWXQpjr/h7ap9sz39IF6qMpWHn9KJSLP4P/ERkZh8wclk=
  gem: swagger_docs_generator
  on:
    repo: Dev-Crea/swagger-docs-generator
    all_branches: true
  skip_cleanup: true

notifications:
  email: false
  slack:
    on_success: always
    rooms:
      secure: wq9V5QaS9tQPr0gaHtRCuLPbMei+gO6tHNwkDFbNUo9SFb1W/0zdxapnxQhxIcyqYfLanvnjprQHme3OXJnVP59jbG4CIfe0NMcOO4s+DYBJvEBEj2+li263A96mJCdXxVojDEZ83E/0+PppfNut+CBtvWikAkMyvvbPNyd0XkQ7dYK6iWEdLBRjDmC8HYRPZgLAcHADB85F60/BuUwsWkZhCyymAXU1McPVFu8OMBpb7LJhLy9MqB5W6VpOlmUYDeTasl5h+tV7ci2cr8Mcu6EAuSUWMG/bBm57z65cEG7kz750gw1Vt8h+mUgcmWfsXBbsJZrh7xpHOulynMcf0rwVcqanvfb9suHYHf0HXon9+ljlwbP2J91wrQqezmvZqhpekPYXD3Qz8qCtdSzhSOdVzE6LaAtDKrj6p9CJ1hwhp5tWUA1roz8pNdKCOHNkmcrWCOggnhDlxrBkwwVoDvVfIl9yL1kezL87mD8vRrSJWRzKjoE85fjFJM9JR6Ie/Bcf4FjWeWRNwAv4LrLOUBDI8Bs0KNdsw+pK/69EEG5N5gnqGmqs6KOY7Ucs75Hq3ZWop85GFocQnw0k4U6YarDvzrTKz/hcrSTCwnNG8jkpKRQ6x+76rlLPcXwaGkL34AmVJ7SFu8a5u8UJUYigPej6c58rBg5wwcvw++izUKg=
